config/routes.rb
require 'subdomain'

Debateaberto::Application.routes.draw do
  post '/canais', to: 'canais#create'
  put '/canais/:id', to: 'canais#update', as: :canal
  delete '/canais/:id', to: 'canais#destroy'

  resources :mensagens

  constraints(Subdomain::Principal) do
    get '/canais', to: 'canais#index'
    get '/canais/novo', to: 'canais#new', as: :new_canal
  end

  constraints(Subdomain::Canal) do
    get '', to: 'canais#show'
    get '/editar', to: 'canais#edit', as: :edit_canal
  end

  devise_for :usuarios, skip: [:sessions, :passwords, :registrations],
    controllers: { omniauth_callbacks: 'usuarios/omniauth_callbacks' }

  devise_scope :usuario do
    # login/logout
    post '/entrar' => 'devise/sessions#create', as: :usuario_session
    delete '/sair' => 'devise/sessions#destroy', as: :destroy_usuario_session
    
    # resetar/trocar senha
    post '/recuperar_senha' => 'devise/passwords#create', as: :usuario_password
    get '/minha_conta/senha/editar' => 'devise/passwords#edit', as: :edit_usuario_password
    put '/minha_conta/senha/editar' => 'devise/passwords#update'

    # configurações do usuário
    post '/cadastrar' => 'devise/registrations#create', as: :usuario_registration
    get '/minha_conta/editar' => 'devise/registrations#edit', as: :edit_usuario_registration
    put '/minha_conta' => 'devise/registrations#update'
    get '/minha_conta/cancelar' => 'devise/registrations#cancel', as: :cancel_usuario_registration
    delete '/minha_conta' => 'devise/registrations#destroy'
  end

  root to: 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(usuario)
    usuario ||= Usuario.new

    if usuario.papel == 'administrador'
      can :manage, :all
    else
      can :read, :all
      can :create, Canal do |canal|
        usuario.persisted?
      end
      can :create, Mensagem do |mensagem|
        usuario.persisted?
      end
      can [:update, :destroy], Canal do |canal|
        canal.try(:usuario) == usuario || usuario.papel == 'moderador'
      end
    end
  end
end

app/models/canal.rb
class Canal < ActiveRecord::Base
  validates :path, presence: true, uniqueness: true,
                   format: { with: /^[a-z\d]+(-[a-z\d]+)*$/i }
  validates :nome, presence: true

  attr_accessible :descricao, :nome, :path

  belongs_to :usuario
  has_one :streamming
  has_one :twitter
  has_many :mensagens
end

app/models/mensagem.rb
class Mensagem < ActiveRecord::Base
  attr_accessible :content
  belongs_to :usuario
  belongs_to :canal

  def primeira_do_dia?
    first = Mensagem.where('DATE(created_at) = DATE(?)', self.created_at).first
    return true if first == self
  end
end

app/models/perfil.rb
class Perfil < ActiveRecord::Base
  attr_accessible :bairro, :cidade, :descricao, :estado, :nome

  belongs_to :usuario
end

app/models/streamming.rb
class Streamming < ActiveRecord::Base
  belongs_to :canal
  attr_accessible :uri
end

app/models/twitter.rb
class Twitter < ActiveRecord::Base
  belongs_to :canal
  attr_accessible :altura, :busca, :titulo, :descricao
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :nome

  attr_accessor :nome

  has_one :perfil
  has_many :canais
  has_many :mensagens

  validates :papel, inclusion: { in: %w(administrador administrador moderador usuario) }

  before_validation :define_papel_padrao

  before_save do
    self.perfil ||= Perfil.new
    if self.nome
      self.perfil.nome = self.nome
      self.perfil.save
    end
  end

  def self.find_or_create_from_auth_hash(auth_hash)
    if usuario = self.find_by_email(auth_hash.info.email)
      usuario
    else
      usuario = self.create(email: auth_hash.info.email, password: Devise.friendly_token[0, 20]) 
      usuario.nome = auth_hash.info.name
      usuario
    end
  end

  private
  def define_papel_padrao
    self.papel ||= 'usuario'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_ability
    @current_ability ||= Ability.new(current_usuario)
  end
end

app/controllers/canais_controller.rb
class CanaisController < ApplicationController
  load_and_authorize_resource

  # GET /canais
  # GET /canais.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @canais }
    end
  end

  # GET /canais/1
  # GET /canais/1.json
  def show
    @canal = Canal.find_by_path!(request.subdomain)
    @mensagens = @canal.mensagens.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @canal }
    end
  end

  # GET /canais/new
  # GET /canais/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @canal }
    end
  end

  # POST /canais
  # POST /canais.json
  def create
    @canal.usuario = current_usuario
    @canal.streamming = Streamming.create params[:streamming]

    respond_to do |format|
      if @canal.save
        format.html { redirect_to root_url(subdomain: @canal.path),
          notice: 'Canal was successfully created.' }
        format.json { render json: @canal, status: :created, location: @canal }
      else
        format.html { render action: "new" }
        format.json { render json: @canal.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @canal = Canal.find_by_path!(request.subdomain)
    authorize! :update, @canal
  end

  # PUT /canais/1
  # PUT /canais/1.json
  def update
    respond_to do |format|
      if @canal.update_attributes(params[:canal])
        format.html { redirect_to root_url(subdomain: @canal.path),
          notice: 'Canal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @canal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /canais/1
  # DELETE /canais/1.json
  def destroy
    @canal.destroy

    respond_to do |format|
      format.html { redirect_to canais_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/mensagens_controller.rb
class MensagensController < ApplicationController
  load_and_authorize_resource

  rescue_from CanCan::AccessDenied do |exception|
    render 'shared/autentica', layout: false
  end

  def create
    @canal = Canal.find_by_path!(request.subdomain)
    @mensagem.canal = @canal
    @mensagem.usuario = current_usuario
    @mensagem.save
    @mensagem
  end

  def destroy
    @mensagem.destroy
    redirect_to root_url(subdomain: @mensagem.canal.path)
  end
end

app/controllers/usuarios/omniauth_callbacks_controller.rb
class Usuarios::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    auth_user
  end

  def failure
    render layout: false
  end

  protected
  def auth_hash
    env['omniauth.auth']
  end

  def auth_user
    @usuario = Usuario.find_or_create_from_auth_hash(auth_hash)
    sign_in @usuario
    render json: @usuario
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def usuario_omniauth_authorize_url(provider, options = {})
    url = root_url(options).gsub(/\/$/, '')
    path = usuario_omniauth_authorize_path(provider)
    "#{url}#{path}"
  end
end

app/helpers/canais_helper.rb
module CanaisHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mensagens_helper.rb
module MensagensHelper
end

app/views/canais/_form.html.erb
<%= form_for(@canal) do |f| %>
  <% if @canal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@canal.errors.count, "error") %> prohibited this canal from being saved:</h2>

      <ul>
      <% @canal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :path %><br />
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= label_tag 'streamming_uri', 'Icecast streamming URI' %><br />
    <%= text_field_tag 'streamming[uri]', nil %>
  </div>
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/canais/edit.html.erb
<h1>Editing canal</h1>

<%= render 'form' %>

<%= link_to 'Back', root_url(subdomain: @canal.path) %>

app/views/canais/index.html.erb
<h1>Listing canais</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Descricao</th>
  </tr>

<% @canais.each do |canal| %>
  <tr>
    <td><%= link_to canal.nome, root_url(subdomain: canal.path) %></td>
    <td><%= truncate canal.descricao %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Canal', new_canal_path %>

app/views/canais/new.html.erb
<h1>New canal</h1>

<%= render 'form' %>

<%= link_to 'Back', canais_path %>

app/views/canais/show.html.erb
<div class="span7">
  <h2><%= @canal.nome %></h2>

  <video id="streaming" class="video-js vjs-default-skin" controls
    autoplay width="540" height="335" data-setup="{}">
    <source src="<%= @canal.streamming.uri %>" type='video/ogg; codecs="theora, vorbis"'>
    <applet code="com.fluendo.player.Cortado.class" archive="http://theora.org/cortado.jar" width="352" height="288">
      <param name="url" value="<%= @canal.streamming.uri %>"/> 
    </applet>
  </video>

  <div class="info">
    <div class="meta">
      <div class="telespectadores">
      </div>
      <!-- AddThis Button BEGIN -->
      <div class="addthis_toolbox addthis_default_style ">
        <a class="addthis_button_preferred_1"></a>
        <a class="addthis_button_preferred_2"></a>
        <a class="addthis_button_preferred_3"></a>
      </div>
      <script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
      <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4fc3d12a73816701"></script>
      <!-- AddThis Button END -->
    </div>
  </div>

  <% if @canal.descricao.present? %>
    <div class="desc">
      <%= raw @canal.descricao %>
    </div>
  <% end %>
</div>

<div class="span5">
  <%= form_for(Mensagem.new, remote: true) do |f| %>
    <div class="msgs">
      <ul id="chat">
        <% if @canal.mensagens.any? %>
          <%= render @mensagens %>
        <% else %>
          <li>Nenhuma mensagem enviada.</li>
        <% end %>
      </ul>
    </div>

    <div class="actions">
      <%= f.text_field :content, placeholder: @placeholder, maxlength: 255 %>
      <%= f.submit 'Enviar', class: 'btn btn-primary' %>
    </div>
  <% end %>

  <script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
  <script>
    new TWTR.Widget({
      version: 2,
      type: 'search',
      search: '<%= @canal.twitter.busca %>',
      interval: 30000,
      title: '<%= @canal.twitter.titulo %>',
      subject: '<%= @canal.twitter.descricao %>',
      width: 'auto',
      height: <%= @canal.twitter.altura %>,
      theme: {
        shell: {
          background: '#8ec1da',
          color: '#ffffff'
        },
        tweets: {
          background: '#ffffff',
          color: '#444444',
          links: '#1985b5'
        }
      },
      features: {
        scrollbar: true,
        loop: true,
        live: true,
        behavior: 'all'
      }
    }).render().start();
  </script>
</div>

<% content_for :script do %>
  <%= subscribe_to "/#{@canal.id}/mensagens/new" %>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : 'Debate Aberto' %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag 'application', :media => 'all' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_url %>">Debate Aberto</a>
          <div class="container nav-collapse">
            <ul class="nav pull-right painel">
              <% if usuario_signed_in? %>
                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <%= current_usuario.email %>
                    <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to destroy_usuario_session_path, method: :delete do %>
                        <i class="icon-off"></i> Sair
                      <% end %>
                    </li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to 'Entrar / Cadastro', '#entrar', 'data-toggle' => 'modal' %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <%= yield %>
      </div><!--/row-->

      <footer>
        <p>
          <a href="http://creativecommons.org/licenses/by/3.0/" target="_blank">CC-BY</a>
          <a href="http://www.secretariageral.gov.br/" target="_blank">Secretaria-Geral da Presidência da República</a>,
          <a href="https://www.serpro.gov.br/" target="_blank">Serviço Federal de Processamento de Dados</a>
          - O código desta aplicação está disponível sobre a licensa
          <a target="_blank" href="http://www.gnu.org/licenses/agpl-3.0.html">AGPLv3</a> no
          <a target="_blank" href="https://marcosmlopes@github.com/marcosmlopes/debateaberto.git">github.com</a>
        </p>
      </footer>

    </div> <!-- /container -->

    <div class="modal hide" id="entrar">
      <%= render 'shared/entrar' %>
    </div>

    <div class="modal hide" id="cadastrar">
      <%= render 'shared/cadastrar' %>
    </div>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_tag do %>
      window.fbAppId = '<%= CONFIG['facebook_app_id'] %>';
    <% end %>
    <%= javascript_include_tag 'application' %>
    <%= yield :script %>

  </body>
</html>

app/views/mensagens/_mensagem.html.erb
<% if mensagem.primeira_do_dia? %>
  <li class="separador-dia <%= "hoje" if mensagem.created_at.day == Time.now.day %>">
    <span class="hr"></span>
    <strong><i class="icon-arrow-down"></i> <%= mensagem.created_at.strftime("%d/%m/%Y") %> <i class="icon-arrow-down"></i></strong>
  </li>
<% end %>
<li class="<%= "hoje" if mensagem.created_at.day == Time.now.day %>">
  <span class="created_at"><%= mensagem.created_at.strftime("%H:%M") %></span>
  <strong><%= mensagem.usuario.perfil.nome %></strong>: <%= mensagem.content %>
  <% if current_usuario.try(:papel) == 'administrador' %>
    <%= link_to mensagem, method: :delete, confirm: 'Tem certeza?' do %>
      <i class="icon-trash"></i>
    <% end %>
  <% end %>
</li>

app/views/mensagens/create.js.erb
<% publish_to "/#{@canal.id}/mensagens/new" do %>
  $elem = $("#chat");
  $elem.append("<%= j render(@mensagem) %>");
  $elem.scrollTop($elem[0].scrollHeight);
<% end %>
$("#mensagem_content").val('');

app/views/shared/_cadastrar.html.erb
<div class="modal-header">
  <button class="close" data-dismiss="modal">×</button>
  <h1>Cadastrar</h1>
</div>

<%= form_tag usuario_registration_path do %>
  <div class="modal-body">
    <div class="control-group">
      <%= label_tag 'usuario_nome', 'Nome:' %>
      <div class="controls">
        <%= text_field_tag 'usuario[nome]', nil, required: true, autofocus: true %>
      </div>
    </div>

    <div class="control-group">
      <%= label_tag 'usuario_email_cadastro', 'E-mail:' %>
      <div class="controls">
        <%= email_field_tag 'usuario[email]', nil, required: true,
          pattern: '^[a-zA-Z0-9-\_.]+@[a-zA-Z0-9-\_.]+\.[a-zA-Z0-9.]{2,5}$',
          id: :usuario_email_cadastro %>
      </div>
    </div>

    <div class="control-group">
      <%= label_tag 'usuario_password_cadastro', 'Senha:' %>
      <div class="controls">
        <%= password_field_tag 'usuario[password]', nil, required: true,
          id: :usuario_password_cadastro %>
      </div>
    </div>

    <div class="control-group">
      <%= label_tag 'usuario_password_confirmation', 'Confirmação de senha:' %>
      <div class="controls">
        <%= password_field_tag 'usuario[password_confirmation]', nil, required: true %>
      </div>
    </div>
  </div>

  <div class="modal-footer">
    <%= link_to 'Cancelar', '#', 'data-dismiss' => 'modal', class: 'btn' %>
    <%= submit_tag 'Cadastrar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/shared/_entrar.html.erb
<div class="modal-header">
  <button class="close" data-dismiss="modal">×</button>
  <h1>Entrar</h1>
</div>

<%= form_tag usuario_session_path do %>
  <div class="modal-body">
    <p>
      Não possui uma conta?
      <%= link_to 'Cadastre-se', '#cadastrar', 'data-toggle' => 'modal', class: 'cadastrar' %>
      ou entre utilizando sua conta do:
    </p>

    <ul class="provedores">
      <li><%= link_to 'Facebook', usuario_omniauth_authorize_url(:facebook, subdomain: false),
        class: 'facebook', title: 'Facebook', 'data-width' => 600,
        'data-height' => 400 %></li>
    </ul>

    <div class="control-group">
      <%= label_tag 'usuario_email', 'E-mail:' %>
      <div class="controls">
        <%= email_field_tag 'usuario[email]', nil, required: true, autofocus: true,
          pattern: '^[a-zA-Z0-9-\_.]+@[a-zA-Z0-9-\_.]+\.[a-zA-Z0-9.]{2,5}$' %>
      </div>
    </div>

    <div class="control-group">
      <%= label_tag 'usuario_password', 'Senha:' %>
      <div class="controls">
        <%= password_field_tag 'usuario[password]', nil, required: true %>
      </div>
    </div>

    <%= label_tag 'usuario_remember_me', class: 'checkbox' do %>
      <%= hidden_field_tag 'usuario[remember_me]', 0, id: nil %>
      <%= check_box_tag 'usuario[remember_me]', 1 %>
      Lembrar-me
    <% end %>
  </div>

  <div class="modal-footer">
    <%= link_to 'Cancelar', '#', 'data-dismiss' => 'modal', class: 'btn' %>
    <%= submit_tag 'Entrar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/shared/_recuperar_senha.html.erb
<div class="modal-header">
  <button class="close" data-dismiss="modal">×</button>
  <h1>Recuperar senha</h1>
</div>

<%= form_tag usuario_password_path do %>
  <div class="modal-body">
    <p>Informe o e-mail da sua conta para que possamos lhe enviar por e-mail
      os próximos passos para recuperar sua senha.</p>

    <div class="control-group">
      <%= label_tag 'usuario_email', 'E-mail da sua conta:' %>
      <div class="controls">
        <%= email_field_tag 'usuario[email]', nil, required: true, autofocus: true,
          pattern: '^[a-zA-Z0-9-\_.]+@[a-zA-Z0-9-\_.]+\.[a-zA-Z0-9.]{2,5}$' %>
      </div>
    </div>
  </div>

  <div class="modal-footer">
    <%= link_to 'Cancelar', '#', 'data-dismiss' => 'modal', class: 'btn' %>
    <%= submit_tag 'Recuperar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/shared/_recuperar_senha_ok.html.erb
<div class="modal-header">
  <button class="close" data-dismiss="modal">×</button>
  <h1>Recuperar senha</h1>
</div>
<div class="modal-body">
  <p>
    Mandamos um e-mail contendo o link para resetar sua senha.
    <br>
    <%= link_to 'OK', '#', 'data-dismiss' => 'modal', class: 'btn' %></p>
</div>

app/views/shared/autentica.js.erb
$('#entrar').modal('show')